import type { Incident } from "./types";

export const MOCK_INCIDENTS: Incident[] = [
  { Id: 1, INC_Number: "INC-001", Title: "Laptop not connecting to WiFi", Category: { Value: "Network" }, Priority: { Value: "2-High" }, State: { Value: "New" }, Description: "User reports laptop cannot connect to office WiFi since this morning.", CallerID: { Title: "Kedir Hassen", EMail: "kedir@company.com" }, AssignedTo: { Title: "IT Support", EMail: "it@company.com" }, AssignmentGroup: "IT Support", Resolution: "", ResolvedDate: null, Created: "2026-08-27T08:00:00Z", Modified: "2026-08-27T08:00:00Z" },
  { Id: 2, INC_Number: "INC-002", Title: "Email not syncing on mobile", Category: { Value: "Email" }, Priority: { Value: "3-Medium" }, State: { Value: "In Progress" }, Description: "Outlook mobile app not syncing emails for the past 2 days.", CallerID: { Title: "Habib Eshetu", EMail: "habib@company.com" }, AssignedTo: { Title: "IT Support", EMail: "it@company.com" }, AssignmentGroup: "IT Support", Resolution: "", ResolvedDate: null, Created: "2026-08-26T10:00:00Z", Modified: "2026-08-26T10:00:00Z" },
  { Id: 3, INC_Number: "INC-003", Title: "Printer offline in Room 204", Category: { Value: "Hardware" }, Priority: { Value: "3-Medium" }, State: { Value: "On Hold" }, Description: "Network printer shows offline. Restarting did not help.", CallerID: { Title: "Sara Ahmed", EMail: "sara@company.com" }, AssignedTo: null, AssignmentGroup: "", Resolution: "", ResolvedDate: null, Created: "2026-08-25T14:00:00Z", Modified: "2026-08-25T14:00:00Z" },
  { Id: 4, INC_Number: "INC-004", Title: "VPN access issue", Category: { Value: "Network" }, Priority: { Value: "1-Critical" }, State: { Value: "New" }, Description: "Cannot connect to VPN from home. Error: authentication failed.", CallerID: { Title: "Ali Hassan", EMail: "ali@company.com" }, AssignedTo: { Title: "Network Team", EMail: "network@company.com" }, AssignmentGroup: "Network", Resolution: "", ResolvedDate: null, Created: "2026-08-27T09:30:00Z", Modified: "2026-08-27T09:30:00Z" },
  { Id: 5, INC_Number: "INC-005", Title: "Software license expired", Category: { Value: "Software" }, Priority: { Value: "2-High" }, State: { Value: "Resolved" }, Description: "Adobe license expired. User cannot open any Adobe apps.", CallerID: { Title: "Marta Bekele", EMail: "marta@company.com" }, AssignedTo: { Title: "IT Support", EMail: "it@company.com" }, AssignmentGroup: "IT Support", Resolution: "License renewed and activated.", ResolvedDate: "2026-08-27T11:00:00Z", Created: "2026-08-24T08:00:00Z", Modified: "2026-08-27T11:00:00Z" },
  { Id: 6, INC_Number: "INC-006", Title: "Monitor flickering", Category: { Value: "Hardware" }, Priority: { Value: "3-Medium" }, State: { Value: "New" }, Description: "External monitor flickers every few minutes.", CallerID: { Title: "Dawit Tadesse", EMail: "dawit@company.com" }, AssignedTo: null, AssignmentGroup: "", Resolution: "", ResolvedDate: null, Created: "2026-08-27T11:00:00Z", Modified: "2026-08-27T11:00:00Z" },
  { Id: 7, INC_Number: "INC-007", Title: "Keyboard not working", Category: { Value: "Hardware" }, Priority: { Value: "4-Low" }, State: { Value: "Closed" }, Description: "Some keys not registering on keyboard.", CallerID: { Title: "Liya Girma", EMail: "liya@company.com" }, AssignedTo: { Title: "IT Support", EMail: "it@company.com" }, AssignmentGroup: "IT Support", Resolution: "Replaced keyboard.", ResolvedDate: "2026-08-23T15:00:00Z", Created: "2026-08-22T09:00:00Z", Modified: "2026-08-23T15:00:00Z" },
  { Id: 8, INC_Number: "INC-008", Title: "Slow internet speed", Category: { Value: "Network" }, Priority: { Value: "2-High" }, State: { Value: "In Progress" }, Description: "Internet very slow in west wing offices.", CallerID: { Title: "Yonas Tekle", EMail: "yonas@company.com" }, AssignedTo: { Title: "Network Team", EMail: "network@company.com" }, AssignmentGroup: "Network", Resolution: "", ResolvedDate: null, Created: "2026-08-26T13:00:00Z", Modified: "2026-08-26T13:00:00Z" },
];

export const MOCK_REQUESTS = [
  { Id: 1, REQ_Number: "REQ-001", Title: "New laptop for new hire", RequestType: { Value: "Hardware" }, Priority: { Value: "2-High" }, State: { Value: "Open" }, Description: "Need a laptop for John starting next week.", RequestedBy: { Title: "Kedir Hassen", EMail: "kedir@company.com" }, AssignedTo: null, ApprovalStatus: { Value: "Pending" }, DueDate: "2026-09-01", CompletionNotes: "", Created: "2026-08-27T08:00:00Z" },
  { Id: 2, REQ_Number: "REQ-002", Title: "VPN access for remote work", RequestType: { Value: "Access Request" }, Priority: { Value: "3-Medium" }, State: { Value: "Open" }, Description: "Need VPN access to work from home.", RequestedBy: { Title: "Sara Ahmed", EMail: "sara@company.com" }, AssignedTo: null, ApprovalStatus: { Value: "Approved" }, DueDate: null, CompletionNotes: "", Created: "2026-08-26T10:00:00Z" },
  { Id: 3, REQ_Number: "REQ-003", Title: "Adobe Creative Suite license", RequestType: { Value: "Software" }, Priority: { Value: "2-High" }, State: { Value: "Open" }, Description: "Design team needs Adobe CC.", RequestedBy: { Title: "Marta Bekele", EMail: "marta@company.com" }, AssignedTo: null, ApprovalStatus: { Value: "Pending" }, DueDate: "2026-09-05", CompletionNotes: "", Created: "2026-08-26T14:00:00Z" },
  { Id: 4, REQ_Number: "REQ-004", Title: "New employee account setup", RequestType: { Value: "Account Setup" }, Priority: { Value: "1-Critical" }, State: { Value: "Open" }, Description: "New hire starts Monday — needs all accounts.", RequestedBy: { Title: "Ali Hassan", EMail: "ali@company.com" }, AssignedTo: null, ApprovalStatus: { Value: "Approved" }, DueDate: "2026-08-30", CompletionNotes: "", Created: "2026-08-25T09:00:00Z" },
  { Id: 5, REQ_Number: "REQ-005", Title: "Standing desk request", RequestType: { Value: "Hardware" }, Priority: { Value: "4-Low" }, State: { Value: "Closed" }, Description: "Ergonomic standing desk for health reasons.", RequestedBy: { Title: "Liya Girma", EMail: "liya@company.com" }, AssignedTo: null, ApprovalStatus: { Value: "Rejected" }, DueDate: null, CompletionNotes: "Budget not available this quarter.", Created: "2026-08-20T11:00:00Z" },
];